name: auth_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.17
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  mobx_codegen: ^2.7.0
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
